name: Terraform deploy
on:
  push:
    branches:
      - main
env:
    TF_LOG: INFO
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}
    TF_VAR_ECS_CLUSTER: ${{ secrets.TF_VAR_ECS_CLUSTER }}
    TF_VAR_SERVICE_NAME: ${{ secrets.TF_VAR_SERVICE_NAME }}
    TF_VAR_CIDR: ${{ secrets.TF_VAR_CIDR }}
    TF_VAR_SUBCIDR: ${{ secrets.TF_VAR_SUBCIDR }}
    TF_VAR_SECGROUP: ${{ secrets.TF_VAR_SECGROUP }}
    TF_VAR_CTFD_PORT: ${{ secrets.TF_VAR_CTFD_PORT }}
jobs:
  deploy:
    runs-on: "ubuntu-latest"
    environment: secretaf
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.2"
      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"  #create S3 bucket and move the plan to the bucket uncompleted step
      - name: terraform validate
        id: validate
        run: terraform validate
      - name: terraform plan
        id: plan
        run: terraform plan -no-color -input=false
      - name: terraform apply
        id: apply
        run: terraform apply -auto-approve -input=false



